### PR TITLE
1.19 corrupt boat textures

### PR DESCRIPTION
**Pull request by colecrouter**
For some reason, it looks like the new 1.19 boat textures (the actual in-game textures themselves) are corrupt somehow, and the base64-converted-strings don't read often (i.e. Photoshop, upng.js).

I've reencoded the images and replaced them with working ones.

### CODE REVIEW

**Comment by colecrouter** [comment]
Meant to mention these before. You can run a UPNG test on this [repl I found](https://codesandbox.io/s/upng-example-qg6yvp). As well, I noticed when I decoded the images using [this site](https://base64.guru/converter/decode/image/png), it noted that the "MIME types" were incorrect, but not on other PNG files that *do* work.

**Comment by destruc7i0n** [comment]
Oh, it does seem like I included webp there for some reason. Thanks for the PR!

**Comment by colecrouter** [comment]
I noticed that some PNG-to-base64 websites would mark those images as other things (`image/webp`, `byte/octet-stream`, etc.), the images you included weren't actually webps (I checked).

https://www.base64-image.de/ this site for example outputs `image/webp`, specifically for the boat images, and `image/png` for anything else.

**Comment by destruc7i0n** [comment]
Ah yeah I do remember using that site for a bit. Thanks for looking into that

**Pull request merged**
